// EL DICCIONARIO DE DATOS: lo que viaja dentro de cada exportación como «_leeme» y lo que
// sirve /api/export/esquema.json. Escrito para que una persona o una IA entienda cada
// campo sin más contexto. Si cambia una columna, cambia aquí y en docs/DATOS.md.

export const DICCIONARIO = {
  que_es: "Datos del medidor de trabajo clínico: cuánto trabajo operativo cuesta la atención en el PC (tiempo activo, tiempo en el sistema clínico SAP, escritura, clics, pantallas recorridas, esperas del sistema, trabajo posterior a la atención), medido por turno y por paciente, en tres fases del estudio con el mismo instrumento: baseline (sin Miracle), notes (con Miracle Notes) y notes_ops (Notes + Operations).",
  privacidad: "No hay contenido clínico ni texto tecleado en ningún campo. Los pacientes aparecen solo como encounter_key: una huella HMAC irreversible calculada en el PC (misma persona = misma huella dentro del mismo día operativo; entre días no se puede enlazar). Las pantallas SAP son identidades técnicas (sistema/transacción/programa/dynpro), nunca títulos ni valores. Del tecleo solo hay cantidades y tiempo en ráfagas.",
  unidades: "Todos los tiempos terminan en _ms y están en milisegundos (60000 = 1 minuto). Los instantes (_at) son ISO 8601 en UTC. fecha_operativa es la fecha del día operativo del hospital (corte a las 06:00 hora de Bogotá): un turno nocturno que cruza medianoche pertenece al día en que empezó.",
  como_comparar: "Compara fases usando solo turnos con calidad_ok = true (cobertura >= 85 %, sin saltos de reloj, sin datos descartados). Usa medianas por turno, no promedios: los turnos tienen duraciones muy distintas. Para comparaciones pareadas, agrupa por doctor_id y phase. Un turno sin doctor_id es anónimo (nadie eligió su nombre) y mide igual, pero no sirve para comparaciones por médico.",
  definiciones: {
    turno: "Desde que el medidor abre un turno en un PC (al arrancar, al elegir un médico, o cuando vuelve a haber actividad) hasta que se cierra (manual, 4 h sin actividad, 2 h bloqueado, otro médico, apagado). Un cambio de médico son dos turnos.",
    activo: "Tiempo en primer plano con algún clic, tecla o scroll en los últimos 60 segundos. foreground_ms es el tiempo en primer plano sin exigir input.",
    his_ms: "Tiempo activo con SAP (el sistema clínico) en primer plano.",
    post_atencion_ms: "Tiempo activo atribuido a un paciente DESPUÉS de que se abrió otro paciente distinto: lo que se hace sobre A cuando ya se está con B (documentación posterior a la atención).",
    cola_post_turno_ms: "Tiempo activo en SAP después de abrir el último paciente del turno.",
    ready_ms: "Time-to-ready: desde que se llega a una pantalla SAP hasta el primer fin de round-trip con el servidor sin estar ocupado. Nulo (no cero) si nunca llegó.",
    sap_wait_ms: "Suma de round-trips al servidor SAP (StartRequest → EndRequest) durante la visita o el turno: tiempo esperando al sistema.",
    cobertura_pct: "Porcentaje del turno que el medidor vio (tiempo en primer plano medido / duración del turno). Baja cuando el PC se suspende, el medidor muere o el reloj salta.",
    encounter_key: "Huella HMAC-SHA256 (32 hex) del identificador del paciente, calculada en el PC con una clave que cambia cada día operativo. Irreversible. Nula si la pantalla no mostró paciente.",
    teclas_de_control: "Del teclado solo se distinguen seis teclas: Tab, Enter, borrar (Backspace/Supr → correcciones), copiar (Ctrl+C/Ctrl+Ins), pegar (Ctrl+V/Mayús+Ins) y guardar (Ctrl+S). Cualquier otra tecla cuenta solo como «una tecla».",
    interrupciones: "Veces que el médico vuelve a un paciente que ya había abierto antes en el turno (el A→B→A de urgencias).",
    revisitas_sap: "Veces que se vuelve a una pantalla SAP ya visitada con el mismo paciente: navegación de ida y vuelta.",
    consulta_ms: "Duración de una consulta en reloj de pared: del primer al último instante con actividad sobre ese paciente (incluye interrupciones).",
    entre_consultas_ms: "Del último instante con actividad de un paciente al primero del siguiente: cuánto tarda el médico en quedar disponible para el próximo (aproximación al «time to administrative readiness»; el momento físico en que el paciente se va no es observable).",
    carga_admin_pct: "Porcentaje del tiempo activo del turno que fue en SAP (el sistema clínico).",
    surface: "Identidad técnica de la pantalla: sapgui://SISTEMA/TRANSACCION/PROGRAMA/DYNPRO[/subpantalla] para SAP, web://dominio para webs de la lista permitida, o nulo.",
    app: "Aplicación en primer plano normalizada según la config: sap, miracle_web, chrome, edge, firefox, office, uexe, explorador, otro.",
  },
  colecciones: {
    turnos: {
      descripcion: "Una fila por turno con todas las métricas agregadas (tabla shift_summary + shifts). Es la tabla principal para análisis.",
      campos: {
        shift_id: "Identificador único del turno (uuid).",
        fecha_operativa: "Día operativo (YYYY-MM-DD, corte 06:00 Bogotá).",
        phase: "Fase del estudio del turno: baseline | notes | notes_ops (derivada del calendario por fecha).",
        doctor_id: "Id del médico (uuid) o nulo si el turno fue anónimo.",
        medico: "Nombre del médico del roster, o nulo.",
        device_id: "Id del PC (uuid).",
        pc: "Nombre del PC (machine_name).",
        pc_etiqueta: "Etiqueta puesta en el panel (p. ej. consultorio 3).",
        started_at: "Apertura del turno (ISO UTC).",
        ended_at: "Cierre del turno (ISO UTC) o nulo si sigue abierto.",
        end_reason: "Causa del cierre: manual | timeout_inactividad | lock_prolongado | turno_nuevo | apagado | desconocido.",
        duracion_ms: "ended_at − started_at (o hasta ahora si sigue abierto).",
        foreground_ms_total: "Tiempo medido en primer plano (sin exigir input).",
        active_ms_total: "Tiempo activo total (con input en los últimos 60 s).",
        his_ms: "Tiempo activo en SAP.",
        miracle_ms: "Tiempo activo en Miracle (app miracle_web).",
        typing_ms: "Tiempo escribiendo, medido por ráfagas de tecleo.",
        keystrokes: "Cantidad de teclas pulsadas (nunca cuáles).",
        clicks: "Clics izquierdos.",
        scroll_ticks: "Muescas de rueda.",
        context_switches: "Cambios de app, pantalla o paciente.",
        encounters: "Pacientes distintos identificados en SAP en el turno.",
        encounter_active_ms_mediana: "Mediana del tiempo activo por paciente en el turno.",
        post_atencion_ms: "Ver definiciones.post_atencion_ms.",
        cola_post_turno_ms: "Ver definiciones.cola_post_turno_ms.",
        sap_wait_ms_total: "Suma de esperas al servidor SAP en el turno.",
        sap_roundtrips: "Cantidad de round-trips al servidor SAP.",
        ready_ms_p50: "Mediana del time-to-ready de las pantallas SAP del turno (nulo si no hubo).",
        ready_ms_p95: "Percentil 95 del time-to-ready.",
        pantallas_distintas: "Pantallas SAP distintas visitadas.",
        visitas: "Visitas a pantallas SAP (una visita = una estadía).",
        tabs: "Pulsaciones de Tab (navegación entre campos).", enters: "Pulsaciones de Enter (confirmar).",
        correcciones: "Backspace + Supr.", copias: "Copiar (Ctrl+C / Ctrl+Ins).", pegados: "Pegar (Ctrl+V / Mayús+Ins).", guardados: "Ctrl+S.",
        interrupciones: "Ver definiciones.interrupciones.", revisitas_sap: "Ver definiciones.revisitas_sap.",
        consultas_por_hora: "Pacientes distintos por hora de turno.",
        consulta_ms_mediana: "Mediana de la duración de consulta (ver definiciones.consulta_ms).",
        entre_consultas_ms_mediana: "Mediana del tiempo entre consultas (ver definiciones.entre_consultas_ms).",
        carga_admin_pct: "Ver definiciones.carga_admin_pct.",
        cobertura_pct: "Ver definiciones.cobertura_pct.",
        calidad_ok: "true si el turno es comparable (cobertura >= 85, clock_jumps = 0, spool_dropped = 0).",
        active_ms_por_app: "Objeto {app: ms activos}.",
        sap_user_seen: "Usuario de SAP visto en el turno (login del médico, no del paciente).",
        app_version: "Versión del medidor.",
        huecos_ms: "Tiempo que el reloj del medidor no vio (suspensiones, cuelgues).",
        clock_jumps: "Saltos del reloj del PC detectados.",
        spool_dropped: "Filas descartadas en el PC por falta de espacio (nunca en silencio).",
        hooks_degradados: "true si no se pudieron instalar los ganchos de teclado/ratón (sin conteo de clics ni teclas; el activo se estima por último input).",
        ticks_sap_saltados_busy: "Lecturas de SAP saltadas porque SAP estaba ocupado (round-trip en curso).",
        algo_version: "Versión del algoritmo de resumen (3 = post-atención por paciente siguiente + interrupciones, revisitas, consultas por hora, duración y tiempo entre consultas).",
      },
    },
    muestras: {
      descripcion: "La serie temporal cruda: una fila por cubeta de 15 segundos y contexto (app · pantalla · paciente). Es lo que suma a los turnos. Grande: ~4.000 filas por turno.",
      campos: {
        shift_id: "Turno.", device_id: "PC.", doctor_id: "Médico del turno o nulo.", phase: "Fase del turno.",
        bucket_start: "Inicio de la cubeta de 15 s (ISO UTC, alineada al reloj de pared).",
        bucket_ms: "Milisegundos de la cubeta que esta fila cubre (15000 salvo al partirse).",
        seq: "Índice del segmento dentro de la cubeta cuando cambió el contexto a mitad (0, 1, 2…).",
        app: "Aplicación normalizada.", surface: "Pantalla (ver definiciones.surface).", encounter_key: "Huella del paciente o nulo.",
        foreground_ms: "Ms en primer plano.", active_ms: "Ms activos.", typing_ms: "Ms escribiendo.", keystrokes: "Teclas.", clicks: "Clics.",
        scroll_ticks: "Scroll.", context_switches: "Cambios de contexto en la cubeta.", sap_roundtrips: "Round-trips al servidor SAP en la cubeta.", sap_wait_ms: "Espera al servidor SAP en la cubeta (ms).",
        tabs: "Tab.", enters: "Enter.", correcciones: "Backspace + Supr.", copias: "Copiar.", pegados: "Pegar.", guardados: "Ctrl+S.",
      },
    },
    visitas_sap: {
      descripcion: "Una fila por estadía en una pantalla SAP: el recorrido por el sistema clínico, en orden.",
      campos: {
        shift_id: "Turno.", device_id: "PC.", doctor_id: "Médico o nulo.", phase: "Fase.", encounter_key: "Paciente (huella) vigente al salir de la pantalla, o nulo.",
        sid: "Sistema SAP (p. ej. PRD).", tcode: "Transacción (p. ej. NV2000, NWP1).", dynpro: "Número de pantalla (4 dígitos).", surface: "Identidad completa de la pantalla.",
        entered_at: "Llegada (ISO UTC).", left_at: "Salida (ISO UTC).", dwell_ms: "Duración de la estadía.",
        ready_ms: "Time-to-ready (nulo si nunca llegó).", sap_wait_ms: "Espera al servidor durante la estadía.", roundtrips: "Round-trips durante la estadía.",
        exit_to: "Transacción a la que se fue después, o nulo si salió de SAP.",
      },
    },
    eventos: {
      descripcion: "Eventos discretos: apertura/cierre de turno, pacientes abiertos/cerrados, bloqueos, pausas, calidad.",
      campos: {
        shift_id: "Turno o nulo.", device_id: "PC.", occurred_at: "Instante (ISO UTC).",
        kind: "Tipo: shift_start, shift_end, doctor_prompted, encounter_enter, encounter_exit, encounter_unknown, lock, unlock, suspend, resume, medidor_start, medidor_stop, pausa_usuario, reanudar_usuario, sap_attach, sap_detach, sap_user_seen, clock_jump, spool_drop, hooks_degradados, config_applied, ops_run, calidad.",
        encounter_key: "Paciente (huella) si aplica.",
        detail: "Objeto con claves de una lista cerrada (reason, ms, count, user, rule, version…). Nunca texto libre.",
      },
    },
    medicos: { descripcion: "El roster: los médicos del estudio.", campos: { id: "uuid.", display_name: "Nombre.", sap_users: "Usuarios SAP asociados.", active: "Si está en el selector." } },
    dispositivos: { descripcion: "Los PCs con el medidor.", campos: { id: "uuid.", machine_name: "Nombre del PC.", label: "Etiqueta.", status: "active | paused | retired.", app_version: "Versión del medidor.", registered_at: "Registro.", last_seen_at: "Último latido." } },
    fases: { descripcion: "Calendario del estudio.", campos: { phase: "baseline | notes | notes_ops.", starts_on: "Desde (fecha).", ends_on: "Hasta (fecha) o nulo." } },
  },
} as const;
